### ISSUE TITLE
Incorrect Usage: flag provided but not defined: -paragraph.count

### ISSUE THREAD

**Issue by certrik** [RTradeLtd/repo-template#5]
Hi @bonedaddy ,
This error is thrown if using one of the examples `./eml-util gfe --paragraph.count 100 --email.count 5000 --emoji.count 100 --outdir=samples/generated` from readme.md .
Error:
`Incorrect Usage: flag provided but not defined: -paragraph.count`

**Comment by RT-nilPointer** [comment]
@certrik Can you reopen the issue here https://github.com/RTradeLtd/ipld-eml/issues

**Comment by certrik** [comment]
Sorry, it appears I somehow switched repos. Reported in the other one. Done.
